---
- name: Install chrony
  ansible.builtin.package:
    name: chrony
    state: present

- name: Set chrony config
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chronyd

- name: Start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Configure firewall for ntp
  ansible.posix.firewalld:
    service: ntp
    permanent: true
    immediate: true
    state: enabled
  when: "'ntp_servers' in group_names"
