---
all:
  vars:
    ansible_user: ansible
  children:
    control:
      hosts:
        ansible01.rangelab.internal:
    vyos:
      hosts:
        vyos01.rangelab.internal:
          lab_address: 10.10.10.3
    dns_servers:
      hosts:
        infra01.rangelab.internal:
    ntp_servers:
      hosts:
        infra01.rangelab.internal:
    rocky:
      vars:
        ansible_python_interpreter: /usr/bin/python3
      hosts:
        infra01.rangelab.internal:
          lab_address: 10.10.10.2
        ansible01.rangelab.internal:
          lab_address: 10.10.10.20
        managed01.rangelab.internal:
          lab_address: 10.10.10.21
