---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    infra01.rangelab.internal:
      lab_address: 10.10.10.2
    ansible01.rangelab.internal:
      lab_address: 10.10.10.20
    managed01.rangelab.internal:
      lab_address: 10.10.10.21
  children:
    control:
      hosts:
        ansible01.rangelab.internal:
    dns_servers:
      hosts:
        infra01.rangelab.internal:
    ntp_servers:
      hosts:
        infra01.rangelab.internal:
