---
management_nodes:
  hosts:
    ansible01.rangelab.local:
      ansible_connection: local
  vars:
    ansible_user: ansible
managed_nodes:
  hosts:
    managed01.rangelab.local:
  vars:
    ansible_user: ansible
