---
- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
- name: Flush journald
  ansible.builtin.command:
    cmd: journalctl --flush
  changed_when: false
